Apple TV support implementation
deszip/BitBot pull request #28
Opened 2020-10-19 08:50 UTC by vladislavsosiuk

2020-10-19 16:34 UTC, deszip requested changes

2020-10-19 16:34 UTC, deszip commented on Bitrise/Storage/Data Sources/BRAccountsDataSource.m
> +    for (BTRAccount *account in [self.accountsFRC fetchedObjects]) {
https://developer.apple.com/documentation/coredata/nsfetchedresultscontroller/1622278-fetchedobjects
'The returned array does not, however, update as managed objects are inserted, modified, or deleted.'

Нада ходить по секциям и брать objects.

2020-10-19 16:34 UTC, deszip commented on Bitrise/Storage/Data Sources/BRAccountsDataSource.m
> +        if (error != nil) {
Лучше проверять результат вызова а не указатель. Бывает error != nil а результат есть.

2020-10-19 17:18 UTC, vladislavsosiuk commented on Bitrise/Storage/Data Sources/BRAccountsDataSource.m
> +    for (BTRAccount *account in [self.accountsFRC fetchedObjects]) {
убрал

2020-10-19 17:18 UTC, vladislavsosiuk commented on Bitrise/Storage/Data Sources/BRAccountsDataSource.m
> +        if (error != nil) {
убрал

2020-10-22 12:50 UTC, deszip approved these changes

2020-10-22 12:50 UTC, merged